name: libsql_dart
description: "Turso/libsql dart client library"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.2.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
